//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollegerEntities : DbContext
    {
        public CollegerEntities()
            : base("name=CollegerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBA_Actividades> TBA_Actividades { get; set; }
        public virtual DbSet<TBA_ActividadesComponentes> TBA_ActividadesComponentes { get; set; }
        public virtual DbSet<TBA_Asignaturas> TBA_Asignaturas { get; set; }
        public virtual DbSet<TBA_AsignaturasPeriodo> TBA_AsignaturasPeriodo { get; set; }
        public virtual DbSet<TBA_Asistencias> TBA_Asistencias { get; set; }
        public virtual DbSet<TBA_AsistenciasGeneral> TBA_AsistenciasGeneral { get; set; }
        public virtual DbSet<TBA_CargaDocente> TBA_CargaDocente { get; set; }
        public virtual DbSet<TBA_Comentarios> TBA_Comentarios { get; set; }
        public virtual DbSet<TBA_ComentariosIndicadores> TBA_ComentariosIndicadores { get; set; }
        public virtual DbSet<TBA_Componentes> TBA_Componentes { get; set; }
        public virtual DbSet<TBA_ComponentesEvaluaciones> TBA_ComponentesEvaluaciones { get; set; }
        public virtual DbSet<TBA_Dimensiones> TBA_Dimensiones { get; set; }
        public virtual DbSet<TBA_Evaluaciones> TBA_Evaluaciones { get; set; }
        public virtual DbSet<TBA_Grupos> TBA_Grupos { get; set; }
        public virtual DbSet<TBA_GruposHorarios> TBA_GruposHorarios { get; set; }
        public virtual DbSet<TBA_Indicadores> TBA_Indicadores { get; set; }
        public virtual DbSet<TBA_Notas> TBA_Notas { get; set; }
        public virtual DbSet<TBA_NotasActividades> TBA_NotasActividades { get; set; }
        public virtual DbSet<TBA_NotasComponentes> TBA_NotasComponentes { get; set; }
        public virtual DbSet<TBA_NotasIndicadores> TBA_NotasIndicadores { get; set; }
        public virtual DbSet<TBA_NotasModificadas> TBA_NotasModificadas { get; set; }
        public virtual DbSet<TBA_Rotaciones> TBA_Rotaciones { get; set; }
        public virtual DbSet<TBA_TiposActividades> TBA_TiposActividades { get; set; }
        public virtual DbSet<TBA_TiposAsignatura> TBA_TiposAsignatura { get; set; }
        public virtual DbSet<TBG_Colegio> TBG_Colegio { get; set; }
        public virtual DbSet<TBG_Coordinaciones> TBG_Coordinaciones { get; set; }
        public virtual DbSet<TBG_Correos> TBG_Correos { get; set; }
        public virtual DbSet<TBG_Cursos> TBG_Cursos { get; set; }
        public virtual DbSet<TBG_CursosPeriodos> TBG_CursosPeriodos { get; set; }
        public virtual DbSet<TBG_Empleados> TBG_Empleados { get; set; }
        public virtual DbSet<TBG_EmpleadosPeriodo> TBG_EmpleadosPeriodo { get; set; }
        public virtual DbSet<TBG_Estudiantes> TBG_Estudiantes { get; set; }
        public virtual DbSet<TBG_EstudiantesGrupos> TBG_EstudiantesGrupos { get; set; }
        public virtual DbSet<TBG_EstudiantesPeriodos> TBG_EstudiantesPeriodos { get; set; }
        public virtual DbSet<TBG_Familias> TBG_Familias { get; set; }
        public virtual DbSet<TBG_Niveles> TBG_Niveles { get; set; }
        public virtual DbSet<TBG_Periodos> TBG_Periodos { get; set; }
        public virtual DbSet<TBG_Personas> TBG_Personas { get; set; }
        public virtual DbSet<TBG_Secciones> TBG_Secciones { get; set; }
        public virtual DbSet<TBG_SeccionesPeriodos> TBG_SeccionesPeriodos { get; set; }
        public virtual DbSet<TBG_Semestres> TBG_Semestres { get; set; }
        public virtual DbSet<TBM_AreasTematicas> TBM_AreasTematicas { get; set; }
        public virtual DbSet<TBM_Aulas> TBM_Aulas { get; set; }
        public virtual DbSet<TBM_AulasPeriodos> TBM_AulasPeriodos { get; set; }
        public virtual DbSet<TBM_CategoriasPago> TBM_CategoriasPago { get; set; }
        public virtual DbSet<TBM_CondicionesAcademicas> TBM_CondicionesAcademicas { get; set; }
        public virtual DbSet<TBM_Departamentos> TBM_Departamentos { get; set; }
        public virtual DbSet<TBM_EstadosAdmision> TBM_EstadosAdmision { get; set; }
        public virtual DbSet<TBM_EstadosCiviles> TBM_EstadosCiviles { get; set; }
        public virtual DbSet<TBM_EstadosSistema> TBM_EstadosSistema { get; set; }
        public virtual DbSet<TBM_Etnias> TBM_Etnias { get; set; }
        public virtual DbSet<TBM_FormasPago> TBM_FormasPago { get; set; }
        public virtual DbSet<TBM_Justificaciones> TBM_Justificaciones { get; set; }
        public virtual DbSet<TBM_Nacionalidades> TBM_Nacionalidades { get; set; }
        public virtual DbSet<TBM_Profesiones> TBM_Profesiones { get; set; }
        public virtual DbSet<TBM_Puestos> TBM_Puestos { get; set; }
        public virtual DbSet<TBM_Rasgos> TBM_Rasgos { get; set; }
        public virtual DbSet<TBM_ResultadosAdmision> TBM_ResultadosAdmision { get; set; }
        public virtual DbSet<TBM_Sexos> TBM_Sexos { get; set; }
        public virtual DbSet<TBM_TiposAulas> TBM_TiposAulas { get; set; }
        public virtual DbSet<TBM_TiposContratos> TBM_TiposContratos { get; set; }
        public virtual DbSet<TBM_TiposCorreo> TBM_TiposCorreo { get; set; }
        public virtual DbSet<TBM_TiposEmpleado> TBM_TiposEmpleado { get; set; }
        public virtual DbSet<TBM_TiposEstudiantes> TBM_TiposEstudiantes { get; set; }
        public virtual DbSet<TBM_TiposEvaluaciones> TBM_TiposEvaluaciones { get; set; }
        public virtual DbSet<TBM_TiposNCF> TBM_TiposNCF { get; set; }
        public virtual DbSet<TBR_Admisiones> TBR_Admisiones { get; set; }
        public virtual DbSet<TBS_AccesosPerfiles> TBS_AccesosPerfiles { get; set; }
        public virtual DbSet<TBS_Modulos> TBS_Modulos { get; set; }
        public virtual DbSet<TBS_Perfiles> TBS_Perfiles { get; set; }
        public virtual DbSet<TBS_SubModulos> TBS_SubModulos { get; set; }
        public virtual DbSet<TBS_TiposUsuario> TBS_TiposUsuario { get; set; }
        public virtual DbSet<TBS_Usuarios> TBS_Usuarios { get; set; }
    }
}
