//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBA_NotasActividades
    {
        public string Matricula { get; set; }
        public System.Guid idActividadComponente { get; set; }
        public Nullable<double> Nota { get; set; }
        public Nullable<double> NotaConducta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaConducta { get; set; }
    }
}
