//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBA_Grupos
    {
        public string idGrupo { get; set; }
        public string Nombre { get; set; }
        public string idPeriodo { get; set; }
        public string idSemestre { get; set; }
        public string idCurso { get; set; }
        public string idSeccion { get; set; }
        public string idAsignatura { get; set; }
        public int Capacidad { get; set; }
    }
}
