//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBA_Asignaturas
    {
        public string idAsignatura { get; set; }
        public string Nombre { get; set; }
        public string NombreOficial { get; set; }
        public string idAreaTematica { get; set; }
        public Nullable<int> Creditos { get; set; }
        public string Observaciones { get; set; }
        public string Prefijo { get; set; }
        public bool bCualitativo { get; set; }
    }
}
