//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBA_ComponentesEvaluaciones
    {
        public System.Guid idComponenteEvaluacion { get; set; }
        public System.Guid idComponente { get; set; }
        public string idEvaluacion { get; set; }
        public string idGrupo { get; set; }
        public string idTipoActividad { get; set; }
        public double Valor { get; set; }
    }
}
