//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBA_Comentarios
    {
        public string Matricula { get; set; }
        public string idPeriodo { get; set; }
        public string idSemestre { get; set; }
        public string idCurso { get; set; }
        public string idEvaluacion { get; set; }
        public string Comentario { get; set; }
    }
}
