//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBA_ActividadesComponentes
    {
        public System.Guid idActividadComponente { get; set; }
        public System.Guid idComponenteEvaluacion { get; set; }
        public System.Guid idActividad { get; set; }
        public double Valor { get; set; }
        public bool bCerrada { get; set; }
    }
}
