//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBA_NotasModificadas
    {
        public System.Guid idModificacion { get; set; }
        public string Matricula { get; set; }
        public System.Guid idActividadComponente { get; set; }
        public Nullable<double> oldNota { get; set; }
        public Nullable<double> Nota { get; set; }
        public Nullable<double> oldNotaConducta { get; set; }
        public Nullable<double> NotaConducta { get; set; }
        public bool bProcesado { get; set; }
        public string Motivo { get; set; }
        public Nullable<int> idEmpleadoRegistra { get; set; }
        public Nullable<int> idEmpleadoProcesa { get; set; }
        public Nullable<int> idEmpleadoAutoriza { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion { get; set; }
    }
}
