//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBA_AsignaturasPeriodo
    {
        public string idPeriodo { get; set; }
        public string idSemestre { get; set; }
        public string idCurso { get; set; }
        public string idAsignatura { get; set; }
        public bool bIndice { get; set; }
        public bool bCostoIncluido { get; set; }
        public bool bBoletin { get; set; }
        public bool bRecord { get; set; }
        public bool bActa { get; set; }
        public Nullable<int> OrdenBoletin { get; set; }
        public Nullable<int> OrdenRecord { get; set; }
        public Nullable<int> OrdenActa { get; set; }
        public string idTipoAsignatura { get; set; }
        public Nullable<int> CreditosAdicionales { get; set; }
    }
}
