//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBG_EstudiantesPeriodos
    {
        public string Matricula { get; set; }
        public string idPeriodo { get; set; }
        public string idCurso { get; set; }
        public string idSeccion { get; set; }
        public Nullable<int> iNoLista { get; set; }
        public string idTipoEstudiante { get; set; }
        public string idCondicionAcademica { get; set; }
        public string idTipoContrato { get; set; }
        public string idCategoriaPago { get; set; }
        public string idFamilia { get; set; }
        public bool bBecado { get; set; }
        public bool bHabilitado { get; set; }
    }
}
