//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBG_EmpleadosPeriodo
    {
        public int idEmpleado { get; set; }
        public string idPeriodo { get; set; }
        public string idTipoEmpleado { get; set; }
        public Nullable<int> idDepartamento { get; set; }
        public Nullable<int> idPuestoTrabajo { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public bool bDocente { get; set; }
        public bool bCoordinador { get; set; }
        public bool bCoordinadorDisciplina { get; set; }
        public string Labor { get; set; }
        public string Comentarios { get; set; }
    }
}
