//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBG_Familias
    {
        public string idFamilia { get; set; }
        public string AnoIngreso { get; set; }
        public string CedulaResponsable { get; set; }
        public bool bRestriccionPagoCK { get; set; }
        public bool bUtilizarNCF { get; set; }
        public string idTipoNCF { get; set; }
        public string BeneficiarioNCF { get; set; }
        public string RNC_CED { get; set; }
        public bool bStatus { get; set; }
        public bool bRestriccionPagoTarjeta { get; set; }
        public string Apellidos { get; set; }
        public string Comentarios { get; set; }
    }
}
