//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBG_Colegio
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string RNC { get; set; }
        public string Codigo { get; set; }
        public string NumeroRegion { get; set; }
        public string NumeroDistrito { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string WebSite { get; set; }
        public string Email { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
        public string Youtube { get; set; }
        public byte[] Logo { get; set; }
        public byte[] LogoWeb { get; set; }
        public string Direccion { get; set; }
        public string idProvincia { get; set; }
        public string idMunicipio { get; set; }
        public string idCiudad { get; set; }
        public string idSector { get; set; }
        public Nullable<bool> bMatutina { get; set; }
        public Nullable<bool> bVespertina { get; set; }
        public Nullable<bool> bNocturna { get; set; }
        public Nullable<bool> bPublica { get; set; }
        public Nullable<bool> bPrivada { get; set; }
        public Nullable<bool> bUrbana { get; set; }
        public Nullable<bool> bRural { get; set; }
        public string CedulaDirector { get; set; }
        public string CedulaDirectorAcademico { get; set; }
        public string CedulaAdministrador { get; set; }
        public string CedulaEncargadoRegistro { get; set; }
        public string Contrato { get; set; }
        public string Firma { get; set; }
        public string EmailEnvio { get; set; }
        public string Password { get; set; }
        public string SMTP { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> bSSL { get; set; }
        public Nullable<int> Puerto { get; set; }
        public Nullable<int> CantidadCorreo { get; set; }
        public string TextoReciboPago { get; set; }
        public string TextoRecordatorioPago { get; set; }
        public string TextoAdmision { get; set; }
        public string DirectorRegional { get; set; }
        public string DirectorDistrital { get; set; }
        public string TecnicoSupervisor { get; set; }
        public string EncargadoCertificaciones { get; set; }
        public string EncargadoPN { get; set; }
        public string UbicacionRegion { get; set; }
        public string UbicacionDistrito { get; set; }
        public string EmailSoporte { get; set; }
    }
}
