//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBG_Estudiantes
    {
        public string Matricula { get; set; }
        public string Nombres { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string idSexo { get; set; }
        public string idEtnia { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public string LugarNac { get; set; }
        public Nullable<int> idNacionalidad { get; set; }
        public string Pasaporte { get; set; }
        public string Email { get; set; }
        public string CedulaMadre { get; set; }
        public string CedulaPadre { get; set; }
        public string CedulaTutor { get; set; }
        public string iVive { get; set; }
        public string iResponsable { get; set; }
        public string idAdmision { get; set; }
        public string idFamilia { get; set; }
        public bool bStatus { get; set; }
    }
}
