//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBG_Correos
    {
        public int idCorreo { get; set; }
        public string Cedula { get; set; }
        public string Correo { get; set; }
        public bool bPrincipal { get; set; }
        public int idTipoCorreo { get; set; }
    }
}
