//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBG_Cursos
    {
        public string idCurso { get; set; }
        public string Curso { get; set; }
        public string NombreOficial { get; set; }
        public int Orden { get; set; }
        public string idNivel { get; set; }
    }
}
