//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM_Aulas
    {
        public string idAula { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Capacidad { get; set; }
        public Nullable<int> idTipoAula { get; set; }
        public string Observaciones { get; set; }
    }
}
