//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM_TiposEvaluaciones
    {
        public string idTipoEvaluacion { get; set; }
        public string TipoEvaluacion { get; set; }
        public string Descripcion { get; set; }
        public int Orden { get; set; }
    }
}
