//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBM_ResultadosAdmision
    {
        public string idResultadoAdmision { get; set; }
        public string ResultadoAdmision { get; set; }
        public bool bAceptable { get; set; }
    }
}
