//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBR_Admisiones
    {
        public string idAdmision { get; set; }
        public string idAdmisionHermano { get; set; }
        public string idFamiliaExistente { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string Nombres { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string idSexo { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public string idCursoSolicitado { get; set; }
        public string InstProcedencia { get; set; }
        public string MotivoAplicacion { get; set; }
        public string CedulaMadre { get; set; }
        public string CedulaPadre { get; set; }
        public string CedulaTutor { get; set; }
        public string idEstadoAdmision { get; set; }
        public string idPeriodo { get; set; }
        public string idCategoriaPago { get; set; }
        public string idFormaPago { get; set; }
        public string Libro { get; set; }
        public string Folio { get; set; }
        public string Acta { get; set; }
        public string Circunscripcion { get; set; }
        public string Filiacion { get; set; }
        public Nullable<bool> bExtranjero { get; set; }
        public string iVive { get; set; }
        public string iResponsable { get; set; }
        public Nullable<int> idNacionalidad { get; set; }
        public string idEtnia { get; set; }
        public string idTipoContrato { get; set; }
        public string LugarNac { get; set; }
        public string Pasaporte { get; set; }
        public string Email { get; set; }
        public string COD_Oficial { get; set; }
        public Nullable<int> idEvaluador { get; set; }
        public string idResultadoAdmision { get; set; }
        public string idCursoAprobado { get; set; }
        public string Observaciones { get; set; }
        public string ObservacionesPsico { get; set; }
        public string MatriculaGenerada { get; set; }
        public string idFamiliaGenerada { get; set; }
        public bool bStatus { get; set; }
    }
}
