//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBS_Perfiles
    {
        public int idPerfil { get; set; }
        public string Perfil { get; set; }
        public Nullable<System.TimeSpan> HoraEntrada { get; set; }
        public Nullable<System.TimeSpan> HoraSalida { get; set; }
        public bool bLunes { get; set; }
        public bool bMartes { get; set; }
        public bool bMiercoles { get; set; }
        public bool bJueves { get; set; }
        public bool bViernes { get; set; }
        public bool bSabado { get; set; }
        public bool bDomingo { get; set; }
        public string idSubModuloPrincipal { get; set; }
        public string idEstadoSistema { get; set; }
    }
}
