//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBS_SubModulos
    {
        public string idSubModulo { get; set; }
        public string Nombre { get; set; }
        public string idModulo { get; set; }
        public bool bPrincipal { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Descripcion { get; set; }
    }
}
