//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBS_Usuarios
    {
        public string Usuario { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public int idPerfil { get; set; }
        public string Identificador { get; set; }
        public string idTipoUsuario { get; set; }
        public bool bForzarPassword { get; set; }
        public bool bHabilitado { get; set; }
    }
}
