//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBS_AccesosPerfiles
    {
        public int idPerfil { get; set; }
        public string idSubModulo { get; set; }
        public bool bAccede { get; set; }
    }
}
